In [11]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[6,7]])
C=A+B
D=A-B
E=A*B
#MATRIX MULTIPLICATION
F=np.dot(A,B)
A_TRANSPOSE=A.T
print("Addition:")
print(C)
print("\nSubtraction:")
print(D)
print("\nElement wise Mutiplication:")
print(E)
print("\nMultiplication:")
print(F)
print("\nA_Transpose:")
print(A_TRANSPOSE)

Addition:
[[ 5  7]
 [ 9 11]]

Subtraction:
[[-3 -3]
 [-3 -3]]

Element wise Mutiplication:
[[ 4 10]
 [18 28]]

Multiplication:
[[16 19]
 [36 43]]

A_Transpose:
[[1 3]
 [2 4]]
