In [5]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform SVD
U,S, VT=np.linalg.svd(X)
#choose the number of component to keep
n_components=2
#reconstruct the matrix with reduced dimensions
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components]))
print("Orginal Matrix")
print(X)
print("\nReconstructed Matrix (with reduced dimension)")
print(X_reconstructed)



Orginal Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

reconstructed Matrix (with reduced dimension)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
